using System;
using System.Collections.Generic;
using Subtitle;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SmiManager
{
    public partial class MainForm : WebForm.WebForm
    {
        #region 초기화

        public MainForm()
        {
            StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            Location = new System.Drawing.Point(554, 0);
            ClientSize = new System.Drawing.Size(1360, 749);
            Name = Text = "Smi Manager";
        }

        public override void InitAfterLoad()
        {
            // 파일 작업할 일이 있나?
            //SetDragEvent("originSmi", DragDropEffects.All, new DropActionDelegate(DropFile));
            //SetClickEvent("btnSplitOrigin", "SplitOrigin");
            //SetClickEvent("btnFrameAssToSmi", "FrameAssToSmi");
            //SetClickEvent("btnJoinFrame", "JoinFrame");

            Dictionary<string, string> param = new Dictionary<string, string>();
            if (true)
            {
                param.Add(".tab[name=fillSync] textarea.input", "<Sync Start=61379><P Class=KRCC>\n"
+ "<font color=\"#cccc88\">I</font><font color=\"#997722\">n the dreaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In</font> <font color=\"#997722\">the dreaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<Sync Start=61687><P Class=KRCC>\n"
+ "<font color=\"#cccc88\">In t</font><font color=\"#997722\">he dreaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In th</font><font color=\"#997722\">e dreaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the</font> <font color=\"#997722\">dreaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<Sync Start=61957><P Class=KRCC>\n"
+ "<font color=\"#cccc88\">In the d</font><font color=\"#997722\">reaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the dr</font><font color=\"#997722\">eaming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the dre</font><font color=\"#997722\">aming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the drea</font><font color=\"#997722\">ming 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<Sync Start=62595><P Class=KRCC>\n"
+ "<font color=\"#cccc88\">In the dream</font><font color=\"#997722\">ing 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the dreami</font><font color=\"#997722\">ng 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the dreamin</font><font color=\"#997722\">g 誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<font color=\"#cccc88\">In the dreaming</font> <font color=\"#997722\">誰かのために</font><br>In the dreaming 누군가를 위해서\n"
+ "<Sync Start=63710><P Class=KRCC>\n"
+ "&nbsp;");
            }
            if (true)
            {
                param.Add(".tab[name=normalizer] textarea.input", "<Sync Start=1000><P Class=KRCC>\n"
+ "asdf\n"
+ "<Sync Start=1250><P Class=KRCC >\n"
+ "가<font color=\"#abcdef\">나</font>다<font color=\"#9abcde\" fade=\"in\">라</font>마<font color=\"#89abcd\" fade=\"out\">바</font>사\n"
+ "<Sync Start=1500><P Class=KRCC >\n"
+ "가<font color=\"#abcdef\">나</font>다<font color=\"#9abcde\">라</font>마<font color=\"#000000\">바</font>사\n"
+ "<Sync Start=2000><P Class=KRCC >\n"
+ "<font typing='keyboard(1,1)'>가각갃각사test가나</font>\n"
+ "<Sync Start=3000><P Class=KRCC >\n"
+ "가각갃각사test가나\n"
+ "<Sync Start=4000><P Class=KRCC>\n"
+ "테스트　　　테스트\n"
+ "<Sync Start=5000><P Class=KRCC>\n"
+ "테스트<font typing='typewriter'>텍스트</font>테스트\n"
+ "<Sync Start=6000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard'>텍스트</font>테스트\n"
+ "<Sync Start=7000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard'>테스트</font>테스트\n"
+ "<Sync Start=8000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard(0,1)'>테스트</font>테스트\n"
+ "<Sync Start=9000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard(1,1)'>테스트</font>테스트\n"
+ "<Sync Start=10000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard'>테test</font>테스트\n"
+ "<Sync Start=11000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard invisible'>테test</font>테스트\n"
+ "<Sync Start=12000><P Class=KRCC>\n"
+ "테스트<font typing='keyboard hangeul'>테test</font><br>테스트\n"
+ "<Sync Start=13000><P Class=KRCC>\n"
+ "테스트테스트테스트");
            }
            if (true)
            {
                param.Add(".tab[name=fusion] textarea.inputSync", "<Sync Start=1354496><P Class=KRCC>\n"
+ "<FONT color=\"#936B9D\">正</FONT><FONT color=\"#4D7397\">しさの裏側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1354839><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正</FONT><FONT color=\"#4D7397\">し</FONT><FONT color=\"#4D7397\">さの裏側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1355167><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正し</FONT><FONT color=\"#4D7397\">さ</FONT><FONT color=\"#4D7397\">の裏側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1356113><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさ</FONT><FONT color=\"#4D7397\">の</FONT><FONT color=\"#4D7397\">裏側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1356256><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの</FONT><FONT color=\"#4D7397\">裏</FONT><FONT color=\"#4D7397\">側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1357362><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの</FONT><FONT color=\"#936B9D\">裏</FONT><FONT color=\"#4D7397\">側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1357743><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏</FONT><FONT color=\"#4D7397\">側</FONT><FONT color=\"#4D7397\">も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1357897><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏</FONT><FONT color=\"#936B9D\">側</FONT><FONT color=\"#4D7397\">も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1358160><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側</FONT><FONT color=\"#4D7397\">も</FONT><FONT color=\"#4D7397\">間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1358505><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も</FONT><FONT color=\"#4D7397\">間</FONT><FONT color=\"#4D7397\">違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1358838><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も間</FONT><FONT color=\"#4D7397\">違</FONT><FONT color=\"#4D7397\">い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1359249><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も間</FONT><FONT color=\"#936B9D\">違</FONT><FONT color=\"#4D7397\">い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1359616><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も間違</FONT><FONT color=\"#4D7397\">い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1359918><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も間違い</FONT><br>올바름의 반대쪽도 잘못\n"
+ "<Sync Start=1360383><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">じゃ</FONT><FONT color=\"#4D7397\">な</FONT><FONT color=\"#4D7397\">いのね</FONT><br>─이 아니겠지\n"
+ "<Sync Start=1362239><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">じゃな</FONT><FONT color=\"#4D7397\">い</FONT><FONT color=\"#4D7397\">のね</FONT><br>─이 아니겠지\n"
+ "<Sync Start=1362429><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">じゃない</FONT><FONT color=\"#4D7397\">の</FONT><FONT color=\"#4D7397\">ね</FONT><br>─이 아니겠지\n"
+ "<Sync Start=1362606><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">じゃないの</FONT><FONT color=\"#4D7397\">ね</FONT><br>─이 아니겠지\n"
+ "<Sync Start=1362772><P Class=KRCC>\n"
+ "<FONT color=\"#D963A3\">じゃないのね</FONT><br>─이 아니겠지");
            }
            if (true)
            {
                param.Add(".tab[name=fusion] textarea.inputText", "<FONT color=\"#936B9D\">正</FONT><FONT color=\"#4D7397\">しさの裏側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正</FONT><FONT color=\"#4D7397\">し</FONT><FONT color=\"#4D7397\">さの裏側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正し</FONT><FONT color=\"#4D7397\">さ</FONT><FONT color=\"#4D7397\">の裏側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさ</FONT><FONT color=\"#4D7397\">の</FONT><FONT color=\"#4D7397\">裏側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの</FONT><FONT color=\"#4D7397\">裏</FONT><FONT color=\"#4D7397\">側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの</FONT><FONT color=\"#936B9D\">裏</FONT><FONT color=\"#4D7397\">側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの裏</FONT><FONT color=\"#4D7397\">側</FONT><FONT color=\"#4D7397\">も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの裏</FONT><FONT color=\"#936B9D\">側</FONT><FONT color=\"#4D7397\">も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの裏側</FONT><FONT color=\"#4D7397\">も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">正しさの裏側も</FONT><br>올바름의 반대쪽도\n"
+ "<FONT color=\"#D963A3\">間</FONT><FONT color=\"#4D7397\">違</FONT><FONT color=\"#4D7397\">いじゃないよね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間</FONT><FONT color=\"#936B9D\">違</FONT><FONT color=\"#4D7397\">いじゃないよね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違</FONT><FONT color=\"#4D7397\">い</FONT><FONT color=\"#4D7397\">じゃないよね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違い</FONT><FONT color=\"#4D7397\">じ</FONT><FONT color=\"#4D7397\">ゃないよね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違いじゃ</FONT><FONT color=\"#4D7397\">な</FONT><FONT color=\"#4D7397\">いよね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違いじゃな</FONT><FONT color=\"#4D7397\">い</FONT><FONT color=\"#4D7397\">よね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違いじゃない</FONT><FONT color=\"#4D7397\">よ</FONT><FONT color=\"#4D7397\">ね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違いじゃないよ</FONT><FONT color=\"#4D7397\">ね</FONT><br>잘못이 아니겠지\n"
+ "<FONT color=\"#D963A3\">間違いじゃないよね</FONT><br>잘못이 아니겠지");
            }
            if (false)
            {
                param.Add(".tab[name=combine] textarea.inputUpper", "<Sync Start=589368><P Class=KRCC>\n"
+ "노래하지 마!\n"
+ "<Sync Start=590777><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=597997><P Class=KRCC>\n"
+ "현혹되지 마라<br>룬으로 느껴라!\n"
+ "<Sync Start=600437><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=620892><P Class=KRCC>\n"
+ "프레이야\n"
+ "<Sync Start=621974><P Class=KRCC >\n"
+ "&nbsp;\n"
+ "<Sync Start=623620><P Class=KRCC>\n"
+ "괜찮아? 미라미라\n"
+ "<Sync Start=625292><P Class=KRCC>\n"
+ "혼자 설 수 있겠어?\n"
+ "<Sync Start=626854><P Class=KRCC >\n"
+ "&nbsp;\n"
+ "<Sync Start=628340><P Class=KRCC>\n"
+ "당연하지\n"
+ "<Sync Start=629444><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=645212><P Class=KRCC>\n"
+ "산개해서 각자 쫓아라!\n"
+ "<Sync Start=647353><P Class=KRCC>\n"
+ "유적의 폴드 에너지가<br>급속히 활성화\n"
+ "<Sync Start=650396><P Class=KRCC>\n"
+ "발퀴레의 폴드파에<br>감응하는 것 같습니다\n"
+ "<Sync Start=653044><P Class=KRCC >\n"
+ "&nbsp;");
            }
            if (false)
            {
                param.Add(".tab[name=combine] textarea.inputLower", "<Sync Start=579908><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">서로 눈이 맞고 사랑을 하고</font></i>\n"
+ "<Sync Start=582972><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">정신없이 뒤쫓아가고</font></i>\n"
+ "<Sync Start=585940><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">그래도 더 자세히 알고 싶어서</font></i>\n"
+ "<Sync Start=588316><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">활활 불타올라</font></i>\n"
+ "<Sync Start=590924><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=591892><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">원할수록 의문이 늘고</font></i>\n"
+ "<Sync Start=594806><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">생각할수록 열이 올라</font></i>\n"
+ "<Sync Start=597806><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">그래서 더 뛰어드는 거야</font></i>\n"
+ "<Sync Start=600311><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">미지의 세계로 ah</font></i>\n"
+ "<Sync Start=604624><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">사랑이나 꿈 같은 건</font></i>\n"
+ "<Sync Start=607525><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">누구나 믿지만</font></i>\n"
+ "<Sync Start=610525><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">거기 거기 공략 안 하면 재미없지</font></i>\n"
+ "<Sync Start=616317><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=616973><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">아슬아슬 사랑</font></i>\n"
+ "<Sync Start=619262><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">위태로운 보더라인</font></i>\n"
+ "<Sync Start=622310><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">난이도 G라도</font></i>\n"
+ "<Sync Start=624454><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">모든 걸 부숴주겠어</font></i>\n"
+ "<Sync Start=628966><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">빙글빙글 날며\n"
+ "<Sync Start=631182><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">한층 더 G로</font></i>\n"
+ "<Sync Start=634183><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">의식이 녹아드네</font></i>\n"
+ "<Sync Start=636399><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">몸은 제어불능</font></i>\n"
+ "<Sync Start=640118><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">가버리겠어</font></i>\n"
+ "<Sync Start=643750><P Class=KRCC>\n"
+ "&nbsp;");
            }
            if (true)
            {
                param.Add(".tab[name=combine] textarea.inputUpper", "<Sync Start=113348><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b>\n"
+ "<Sync Start=124734><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b>\n"
+ "<Sync Start=132345><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b>\n"
+ "<Sync Start=140017><P Class=KRCC>\n"
+ "그 지도자, 제로의 정체는 바로 <br>과거 신성 브리타니아 제국에게<br>버려진 황자  　　　　　　　　<br>를루슈 비 브리타니아 　　　　<br>본인이었다.　　　　　　　　　<b></b>\n"
+ "<Sync Start=147639><P Class=KRCC>\n"
+ "&nbsp;");
            }
            if (true)
            {
                param.Add(".tab[name=combine] textarea.inputLower", "<Sync Start=109569><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行</FONT><FONT color=\"#FF7722\">け</FONT><FONT color=\"#FF7722\">どもけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109682><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行け</FONT><FONT color=\"#FF7722\">ど</FONT><FONT color=\"#FF7722\">もけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109802><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けど</FONT><FONT color=\"#FF7722\">も</FONT><FONT color=\"#FF7722\">けものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109921><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けども</FONT><FONT color=\"#FF7722\">け</FONT><FONT color=\"#FF7722\">ものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110200><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけ</FONT><FONT color=\"#FF7722\">も</FONT><FONT color=\"#FF7722\">のみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110484><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけも</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">みち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110592><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけもの</FONT><FONT color=\"#FF7722\">み</FONT><FONT color=\"#FF7722\">ち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110714><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけものみ</FONT><FONT color=\"#FF7722\">ち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110936><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=111386><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅</FONT><FONT color=\"#FF7722\">子</FONT><FONT color=\"#FF7722\">よ虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111521><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111650><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ</FONT><FONT color=\"#FF7722\">虎</FONT><FONT color=\"#FF7722\">よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111896><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ</FONT><FONT color=\"#B2AA7F\">虎</FONT><FONT color=\"#FF7722\">よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112136><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">と吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112466><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よ</FONT><FONT color=\"#FF7722\">と</FONT><FONT color=\"#FF7722\">吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112572><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと</FONT><FONT color=\"#FF7722\">吠</FONT><FONT color=\"#FF7722\">え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112683><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと吠</FONT><FONT color=\"#FF7722\">え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112932><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=113348><P Class=KRCC>\n"
+ "<FONT color=\"#CC9960\">茜</FONT><FONT color=\"#FF7722\">射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113485><P Class=KRCC>\n"
+ "<FONT color=\"#99BB9E\">茜</FONT><FONT color=\"#FF7722\">射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113627><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜</FONT><FONT color=\"#FF7722\">射</FONT><FONT color=\"#FF7722\">す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113764><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射</FONT><FONT color=\"#FF7722\">す</FONT><FONT color=\"#FF7722\">空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114050><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す</FONT><FONT color=\"#FF7722\">空</FONT><FONT color=\"#FF7722\">の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114291><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す</FONT><FONT color=\"#B2AA7F\">空</FONT><FONT color=\"#FF7722\">の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114410><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114532><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　</FONT><FONT color=\"#FF7722\">彼</FONT><FONT color=\"#FF7722\">方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115115><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　</FONT><FONT color=\"#99BB9E\">彼</FONT><FONT color=\"#FF7722\">方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115252><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼</FONT><FONT color=\"#CC9960\">方</FONT><FONT color=\"#FF7722\">にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115381><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">まほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115508><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方に</FONT><FONT color=\"#FF7722\">ま</FONT><FONT color=\"#FF7722\">ほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115619><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方にま</FONT><FONT color=\"#FF7722\">ほ</FONT><FONT color=\"#FF7722\">ろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115955><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方にまほ</FONT><FONT color=\"#FF7722\">ろ</FONT><FONT color=\"#FF7722\">ば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=116190><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方にまほろ</FONT><FONT color=\"#FF7722\">ば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=116651><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">茜射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=117197><P Class=KRCC>\n"
+ "<FONT color=\"#B2AA7F\">幽</FONT><FONT color=\"#FF7722\">囚の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=117317><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽</FONT><FONT color=\"#FF7722\">囚</FONT><FONT color=\"#FF7722\">の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=117437><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽</FONT><FONT color=\"#B2AA7F\">囚</FONT><FONT color=\"#FF7722\">の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=117572><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=117861><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の</FONT><FONT color=\"#FF7722\">孤</FONT><FONT color=\"#FF7722\">獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=118108><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤</FONT><FONT color=\"#FF7722\">獨</FONT><FONT color=\"#FF7722\">に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=118226><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤</FONT><FONT color=\"#B2AA7F\">獨</FONT><FONT color=\"#FF7722\">に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=118346><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=118594><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　</FONT><FONT color=\"#FF7722\">彷</FONT><FONT color=\"#FF7722\">徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119018><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　</FONT><FONT color=\"#99BB9E\">彷</FONT><FONT color=\"#FF7722\">徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119155><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷</FONT><FONT color=\"#CC9960\">徨</FONT><FONT color=\"#FF7722\">う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119282><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨</FONT><FONT color=\"#FF7722\">う</FONT><FONT color=\"#FF7722\">青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119410><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う</FONT><FONT color=\"#FF7722\">青</FONT><FONT color=\"#FF7722\">春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119739><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う</FONT><FONT color=\"#B2AA7F\">青</FONT><FONT color=\"#FF7722\">春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=119955><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青</FONT><FONT color=\"#FF7722\">春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=120098><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青</FONT><FONT color=\"#B2AA7F\">春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=120242><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=120514><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 \n"
+ "<Sync Start=120958><P Class=KRCC>\n"
+ "<FONT color=\"#B2AA7F\">弱</FONT><FONT color=\"#FF7722\">さと怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121095><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱</FONT><FONT color=\"#FF7722\">さ</FONT><FONT color=\"#FF7722\">と怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121248><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さ</FONT><FONT color=\"#FF7722\">と</FONT><FONT color=\"#FF7722\">怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121373><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと</FONT><FONT color=\"#FF7722\">怒</FONT><FONT color=\"#FF7722\">りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121678><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと</FONT><FONT color=\"#B2AA7F\">怒</FONT><FONT color=\"#FF7722\">りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121887><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒</FONT><FONT color=\"#FF7722\">り</FONT><FONT color=\"#FF7722\">が姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122014><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒り</FONT><FONT color=\"#FF7722\">が</FONT><FONT color=\"#FF7722\">姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122134><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#FF7722\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122559><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#CC9960\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122886><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#99BB9E\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123022><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿</FONT><FONT color=\"#FF7722\">無</FONT><FONT color=\"#FF7722\">き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123143><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無</FONT><FONT color=\"#FF7722\">き</FONT><FONT color=\"#FF7722\">敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123279><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き</FONT><FONT color=\"#FF7722\">敵</FONT><FONT color=\"#FF7722\">ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123398><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き</FONT><FONT color=\"#B2AA7F\">敵</FONT><FONT color=\"#FF7722\">ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123695><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き敵</FONT><FONT color=\"#FF7722\">で</FONT><FONT color=\"#FF7722\">すか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123818><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き敵で</FONT><FONT color=\"#FF7722\">す</FONT><FONT color=\"#FF7722\">か</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124046><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き敵です</FONT><FONT color=\"#FF7722\">か</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124230><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">弱さと怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124734><P Class=KRCC>\n"
+ "<FONT color=\"#B2AA7F\">父</FONT><FONT color=\"#FF7722\">よ　未だ我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125122><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">　未だ我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125249><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　</FONT><FONT color=\"#FF7722\">未</FONT><FONT color=\"#FF7722\">だ我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125471><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　</FONT><FONT color=\"#B2AA7F\">未</FONT><FONT color=\"#FF7722\">だ我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125673><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　未</FONT><FONT color=\"#FF7722\">だ</FONT><FONT color=\"#FF7722\">我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125815><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　未だ</FONT><FONT color=\"#FF7722\">我</FONT><FONT color=\"#FF7722\">は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=125952><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　未だ</FONT><FONT color=\"#B2AA7F\">我</FONT><FONT color=\"#FF7722\">は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=126079><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　未だ我</FONT><FONT color=\"#FF7722\">は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=126201><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">父よ　未だ我は</FONT><br>아버지여, 아직 저는\n"
+ "<Sync Start=126655><P Class=KRCC>\n"
+ "<FONT color=\"#CC9960\">己</FONT><FONT color=\"#FF7722\">を知りがたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=127016><P Class=KRCC>\n"
+ "<FONT color=\"#99BB9E\">己</FONT><FONT color=\"#FF7722\">を知りがたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=127143><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己</FONT><FONT color=\"#FF7722\">を</FONT><FONT color=\"#FF7722\">知りがたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=127378><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を</FONT><FONT color=\"#FF7722\">知</FONT><FONT color=\"#FF7722\">りがたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=127616><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を知</FONT><FONT color=\"#FF7722\">り</FONT><FONT color=\"#FF7722\">がたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=127864><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を知り</FONT><FONT color=\"#FF7722\">が</FONT><FONT color=\"#FF7722\">たし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=128112><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を知りが</FONT><FONT color=\"#FF7722\">た</FONT><FONT color=\"#FF7722\">し</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=128335><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を知りがた</FONT><FONT color=\"#FF7722\">し</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=128583><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">己を知りがたし</FONT><br>제 자신을 알고 싶습니다\n"
+ "<Sync Start=130449><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=132345><P Class=KRCC>\n"
+ "<FONT color=\"#B2AA7F\">先</FONT><FONT color=\"#FF7722\">立つ兄らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=132776><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先</FONT><FONT color=\"#FF7722\">立</FONT><FONT color=\"#FF7722\">つ兄らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=133123><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立</FONT><FONT color=\"#FF7722\">つ</FONT><FONT color=\"#FF7722\">兄らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=133239><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立つ</FONT><FONT color=\"#FF7722\">兄</FONT><FONT color=\"#FF7722\">らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=134247><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立つ</FONT><FONT color=\"#B2AA7F\">兄</FONT><FONT color=\"#FF7722\">らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=134711><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立つ兄</FONT><FONT color=\"#FF7722\">ら</FONT><FONT color=\"#FF7722\">の</FONT><br>앞서간 형들의\n"
+ "<Sync Start=135095><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立つ兄ら</FONT><FONT color=\"#FF7722\">の</FONT><br>앞서간 형들의\n"
+ "<Sync Start=135224><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">先立つ兄らの</FONT><br>앞서간 형들의\n"
+ "<Sync Start=136456><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見</FONT><FONT color=\"#FF7722\">え</FONT><FONT color=\"#FF7722\">ない背中を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=136640><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見え</FONT><FONT color=\"#FF7722\">な</FONT><FONT color=\"#FF7722\">い背中を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=136874><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えな</FONT><FONT color=\"#FF7722\">い</FONT><FONT color=\"#FF7722\">背中を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=137123><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない</FONT><FONT color=\"#FF7722\">背</FONT><FONT color=\"#FF7722\">中を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=137576><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背</FONT><FONT color=\"#FF7722\">中</FONT><FONT color=\"#FF7722\">を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=138071><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背</FONT><FONT color=\"#B2AA7F\">中</FONT><FONT color=\"#FF7722\">を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=138304><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背中</FONT><FONT color=\"#FF7722\">を</FONT><FONT color=\"#FF7722\">追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=138567><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背中を</FONT><FONT color=\"#FF7722\">追</FONT><FONT color=\"#FF7722\">えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=138784><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背中を追</FONT><FONT color=\"#FF7722\">え</FONT><FONT color=\"#FF7722\">ば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=138976><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背中を追え</FONT><FONT color=\"#FF7722\">ば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=139513><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">見えない背中を追えば</FONT><br>보이지 않는 등을 뒤쫓으니\n"
+ "<Sync Start=140017><P Class=KRCC>\n"
+ "<FONT color=\"#B2AA7F\">迷</FONT><FONT color=\"#FF7722\">いの一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140377><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷</FONT><FONT color=\"#FF7722\">い</FONT><FONT color=\"#FF7722\">の一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140769><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷い</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140906><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの</FONT><FONT color=\"#FF7722\">一</FONT><FONT color=\"#FF7722\">夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=141921><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの</FONT><FONT color=\"#B2AA7F\">一</FONT><FONT color=\"#FF7722\">夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142321><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一</FONT><FONT color=\"#FF7722\">夜</FONT><FONT color=\"#FF7722\">に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142729><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142866><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に</FONT><FONT color=\"#FF7722\">明</FONT><FONT color=\"#FF7722\">星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=143817><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に</FONT><FONT color=\"#B2AA7F\">明</FONT><FONT color=\"#FF7722\">星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144017><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明</FONT><FONT color=\"#FF7722\">星</FONT><FONT color=\"#FF7722\">は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144258><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明</FONT><FONT color=\"#B2AA7F\">星</FONT><FONT color=\"#FF7722\">は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144457><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星</FONT><FONT color=\"#FF7722\">は</FONT><FONT color=\"#FF7722\">誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144683><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#FF7722\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145201><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#CC9960\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145361><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#99BB9E\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145530><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星は誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145697><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">迷いの一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=147639><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死</FONT><FONT color=\"#FF7722\">し</FONT><FONT color=\"#FF7722\">て終わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=148344><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死し</FONT><FONT color=\"#FF7722\">て</FONT><FONT color=\"#FF7722\">終わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=148506><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して</FONT><FONT color=\"#FF7722\">終</FONT><FONT color=\"#FF7722\">わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=149296><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終</FONT><FONT color=\"#FF7722\">わ</FONT><FONT color=\"#FF7722\">らぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=149484><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わ</FONT><FONT color=\"#FF7722\">ら</FONT><FONT color=\"#FF7722\">ぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=150161><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わら</FONT><FONT color=\"#FF7722\">ぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=150402><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わらぬ</FONT><br>죽어도 끝나지 않는");
            }
            if (false)
            {
                param.Add(".tab[name=devide] textarea.input", "<Sync Start=579908><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">서로 눈이 맞고 사랑을 하고</font></i>\n"
+ "<Sync Start=582972><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">정신없이 뒤쫓아가고</font></i>\n"
+ "<Sync Start=585940><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">그래도 더 자세히 알고 싶어서</font></i>\n"
+ "<Sync Start=588316><P Class=KRCC>\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">활활 불타올라</font></i>\n"
+ "<Sync Start=589368><P Class=KRCC>\n"
+ "<b></b>　 노래하지 마! 　<b></b><br><b></b>　<i><font color=\"#ff88ff\">활활 불타올라</font></i>　<b></b>\n"
+ "<Sync Start=590777><P Class=KRCC>\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">활활 불타올라</font></i>\n"
+ "<Sync Start=590924><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=591892><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">원할수록 의문이 늘고</font></i>\n"
+ "<Sync Start=594806><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">생각할수록 열이 올라</font></i>\n"
+ "<Sync Start=597806><P Class=KRCC>\n"
+ "<b>　</b><br><b>　</b><br><i><font color=\"#ff88ff\">그래서 더 뛰어드는 거야</font></i>\n"
+ "<Sync Start=597997><P Class=KRCC>\n"
+ "<b></b>　　 현혹되지 마라 　　<b></b><br><b></b>　　 룬으로 느껴라! 　　<b></b><br><i><font color=\"#ff88ff\">그래서 더 뛰어드는 거야</font></i>\n"
+ "<Sync Start=600311><P Class=KRCC>\n"
+ "<b></b>　  현혹되지 마라  　<b></b><br><b></b>　  룬으로 느껴라!  　<b></b><br><b></b>　<i><font color=\"#ff88ff\">미지의 세계로 ah</font></i>　<b></b>\n"
+ "<Sync Start=600437><P Class=KRCC>\n"
+ "<b>　</b><br><b>　</b><br><i><font color=\"#ff88ff\">미지의 세계로 ah</font></i>\n"
+ "<Sync Start=604624><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">사랑이나 꿈 같은 건</font></i>\n"
+ "<Sync Start=607525><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">누구나 믿지만</font></i>\n"
+ "<Sync Start=610525><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">거기 거기 공략 안 하면 재미없지</font></i>\n"
+ "<Sync Start=616317><P Class=KRCC>\n"
+ "&nbsp;\n"
+ "<Sync Start=616973><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">아슬아슬 사랑</font></i>\n"
+ "<Sync Start=619262><P Class=KRCC>\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">위태로운 보더라인</font></i>\n"
+ "<Sync Start=620892><P Class=KRCC>\n"
+ "<b></b>　　 프레이야 　　<b></b><br><i><font color=\"#ff88ff\">위태로운 보더라인</font></i>\n"
+ "<Sync Start=621974><P Class=KRCC >\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">위태로운 보더라인</font></i>\n"
+ "<Sync Start=622310><P Class=KRCC>\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">난이도 G라도</font></i>\n"
+ "<Sync Start=623620><P Class=KRCC>\n"
+ "<b></b>　괜찮아? 미라미라　<b></b><br><b></b>　  <i><font color=\"#ff88ff\">난이도 G라도</font></i>  　<b></b>\n"
+ "<Sync Start=624454><P Class=KRCC>\n"
+ "<b></b>　 괜찮아? 미라미라 　<b></b><br><b></b>　<i><font color=\"#ff88ff\">모든 걸 부숴주겠어</font></i>　<b></b>\n"
+ "<Sync Start=625292><P Class=KRCC>\n"
+ "혼자 설 수 있겠어?<br><i><font color=\"#ff88ff\">모든 걸 부숴주겠어</font></i>\n"
+ "<Sync Start=626854><P Class=KRCC >\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">모든 걸 부숴주겠어</font></i>\n"
+ "<Sync Start=628340><P Class=KRCC>\n"
+ "<b></b>　　 당연하지 　　<b></b><br><i><font color=\"#ff88ff\">모든 걸 부숴주겠어</font></i>\n"
+ "<Sync Start=628966><P Class=KRCC>\n"
+ "<b></b>　 당연하지 　<b></b><br><i><font color=\"#ff88ff\">빙글빙글 날며\n"
+ "<Sync Start=629444><P Class=KRCC>\n"
+ "<b>　</b><br><i><font color=\"#ff88ff\">빙글빙글 날며\n"
+ "<Sync Start=631182><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">한층 더 G로</font></i>\n"
+ "<Sync Start=634183><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">의식이 녹아드네</font></i>\n"
+ "<Sync Start=636399><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">몸은 제어불능</font></i>\n"
+ "<Sync Start=640118><P Class=KRCC>\n"
+ "<i><font color=\"#ff88ff\">가버리겠어</font></i>\n"
+ "<Sync Start=643750><P Class=KRCC>\n"
+ "&nbsp;");
            }
            if (true)
            {
                param.Add(".tab[name=devide] textarea.input", "<Sync Start=109569><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行</FONT><FONT color=\"#FF7722\">け</FONT><FONT color=\"#FF7722\">どもけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109682><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行け</FONT><FONT color=\"#FF7722\">ど</FONT><FONT color=\"#FF7722\">もけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109802><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けど</FONT><FONT color=\"#FF7722\">も</FONT><FONT color=\"#FF7722\">けものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=109921><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けども</FONT><FONT color=\"#FF7722\">け</FONT><FONT color=\"#FF7722\">ものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110200><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけ</FONT><FONT color=\"#FF7722\">も</FONT><FONT color=\"#FF7722\">のみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110484><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけも</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">みち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110592><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけもの</FONT><FONT color=\"#FF7722\">み</FONT><FONT color=\"#FF7722\">ち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110714><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけものみ</FONT><FONT color=\"#FF7722\">ち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=110936><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">行けどもけものみち</FONT><br>간다 해도 짐승의 길\n"
+ "<Sync Start=111386><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅</FONT><FONT color=\"#FF7722\">子</FONT><FONT color=\"#FF7722\">よ虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111521><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111650><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ</FONT><FONT color=\"#FF7722\">虎</FONT><FONT color=\"#FF7722\">よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=111896><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ</FONT><FONT color=\"#B2AA7F\">虎</FONT><FONT color=\"#FF7722\">よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112136><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">と吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112466><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よ</FONT><FONT color=\"#FF7722\">と</FONT><FONT color=\"#FF7722\">吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112572><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと</FONT><FONT color=\"#FF7722\">吠</FONT><FONT color=\"#FF7722\">え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112683><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと吠</FONT><FONT color=\"#FF7722\">え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=112932><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">獅子よ虎よと吠え</FONT><br>사자 호랑이와 함께 짖으며\n"
+ "<Sync Start=113348><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#CC9960\">茜</FONT><FONT color=\"#FF7722\">射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113485><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#99BB9E\">茜</FONT><FONT color=\"#FF7722\">射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113627><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜</FONT><FONT color=\"#FF7722\">射</FONT><FONT color=\"#FF7722\">す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=113764><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射</FONT><FONT color=\"#FF7722\">す</FONT><FONT color=\"#FF7722\">空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114050><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す</FONT><FONT color=\"#FF7722\">空</FONT><FONT color=\"#FF7722\">の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114291><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す</FONT><FONT color=\"#B2AA7F\">空</FONT><FONT color=\"#FF7722\">の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114410><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=114532><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　</FONT><FONT color=\"#FF7722\">彼</FONT><FONT color=\"#FF7722\">方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115115><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　</FONT><FONT color=\"#99BB9E\">彼</FONT><FONT color=\"#FF7722\">方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115252><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼</FONT><FONT color=\"#CC9960\">方</FONT><FONT color=\"#FF7722\">にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115381><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">まほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115508><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方に</FONT><FONT color=\"#FF7722\">ま</FONT><FONT color=\"#FF7722\">ほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115619><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方にま</FONT><FONT color=\"#FF7722\">ほ</FONT><FONT color=\"#FF7722\">ろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=115955><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方にまほ</FONT><FONT color=\"#FF7722\">ろ</FONT><FONT color=\"#FF7722\">ば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=116190><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方にまほろ</FONT><FONT color=\"#FF7722\">ば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=116651><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">茜射す空の　彼方にまほろば</FONT><br>붉게 비치는 하늘 저편의 꿈의 나라\n"
+ "<Sync Start=117197><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#B2AA7F\">幽</FONT><FONT color=\"#FF7722\">囚の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=117317><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽</FONT><FONT color=\"#FF7722\">囚</FONT><FONT color=\"#FF7722\">の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=117437><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽</FONT><FONT color=\"#B2AA7F\">囚</FONT><FONT color=\"#FF7722\">の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=117572><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=117861><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の</FONT><FONT color=\"#FF7722\">孤</FONT><FONT color=\"#FF7722\">獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=118108><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤</FONT><FONT color=\"#FF7722\">獨</FONT><FONT color=\"#FF7722\">に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=118226><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤</FONT><FONT color=\"#B2AA7F\">獨</FONT><FONT color=\"#FF7722\">に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=118346><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=118594><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　</FONT><FONT color=\"#FF7722\">彷</FONT><FONT color=\"#FF7722\">徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119018><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　</FONT><FONT color=\"#99BB9E\">彷</FONT><FONT color=\"#FF7722\">徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119155><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷</FONT><FONT color=\"#CC9960\">徨</FONT><FONT color=\"#FF7722\">う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119282><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨</FONT><FONT color=\"#FF7722\">う</FONT><FONT color=\"#FF7722\">青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119410><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う</FONT><FONT color=\"#FF7722\">青</FONT><FONT color=\"#FF7722\">春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119739><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う</FONT><FONT color=\"#B2AA7F\">青</FONT><FONT color=\"#FF7722\">春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=119955><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青</FONT><FONT color=\"#FF7722\">春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=120098><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青</FONT><FONT color=\"#B2AA7F\">春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=120242><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青春</FONT><FONT color=\"#FF7722\">は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=120514><P Class=KRCC>\n"
+ "황력 2009년　　　　　　　　　　<br>신성 브리타니아 제국은  　　　　<br>황자 를루슈와 황녀 너낼리 남매를<br>대립 관계인 나라  　　　　　　　<br>일본에 인질로 보낸다. 　　　　　<b></b><br><FONT color=\"#66DDDD\">幽囚の孤獨に　彷徨う青春は</FONT><br>감옥 속의 고독에 헤매이는 청춘은 ​\n"
+ "<Sync Start=120958><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#B2AA7F\">弱</FONT><FONT color=\"#FF7722\">さと怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121095><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱</FONT><FONT color=\"#FF7722\">さ</FONT><FONT color=\"#FF7722\">と怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121248><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さ</FONT><FONT color=\"#FF7722\">と</FONT><FONT color=\"#FF7722\">怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121373><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと</FONT><FONT color=\"#FF7722\">怒</FONT><FONT color=\"#FF7722\">りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121678><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと</FONT><FONT color=\"#B2AA7F\">怒</FONT><FONT color=\"#FF7722\">りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=121887><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒</FONT><FONT color=\"#FF7722\">り</FONT><FONT color=\"#FF7722\">が姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122014><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒り</FONT><FONT color=\"#FF7722\">が</FONT><FONT color=\"#FF7722\">姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122134><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#FF7722\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122559><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#CC9960\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=122886><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが</FONT><FONT color=\"#99BB9E\">姿</FONT><FONT color=\"#FF7722\">無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123022><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿</FONT><FONT color=\"#FF7722\">無</FONT><FONT color=\"#FF7722\">き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123143><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無</FONT><FONT color=\"#FF7722\">き</FONT><FONT color=\"#FF7722\">敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123279><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き</FONT><FONT color=\"#FF7722\">敵</FONT><FONT color=\"#FF7722\">ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123398><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き</FONT><FONT color=\"#B2AA7F\">敵</FONT><FONT color=\"#FF7722\">ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123695><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き敵</FONT><FONT color=\"#FF7722\">で</FONT><FONT color=\"#FF7722\">すか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=123818><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き敵で</FONT><FONT color=\"#FF7722\">す</FONT><FONT color=\"#FF7722\">か</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124046><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き敵です</FONT><FONT color=\"#FF7722\">か</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124230><P Class=KRCC>\n"
+ "​ 황력 2009년　　　　　　　　　　 <br> 신성 브리타니아 제국은  　　　　 <br> 황자 를루슈와 황녀 너낼리 남매를 <br> 대립 관계인 나라  　　　　　　　 <br> 일본에 인질로 보낸다. 　　　　　<b></b> <br><FONT color=\"#66DDDD\">弱さと怒りが姿無き敵ですか</FONT><br>연약함과 분노가 형체 없는 적입니까\n"
+ "<Sync Start=124734><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#B2AA7F\">父</FONT><FONT color=\"#FF7722\">よ　未だ我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125122><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父</FONT><FONT color=\"#FF7722\">よ</FONT><FONT color=\"#FF7722\">　未だ我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125249><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　</FONT><FONT color=\"#FF7722\">未</FONT><FONT color=\"#FF7722\">だ我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125471><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　</FONT><FONT color=\"#B2AA7F\">未</FONT><FONT color=\"#FF7722\">だ我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125673><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　未</FONT><FONT color=\"#FF7722\">だ</FONT><FONT color=\"#FF7722\">我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125815><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　未だ</FONT><FONT color=\"#FF7722\">我</FONT><FONT color=\"#FF7722\">は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=125952><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　未だ</FONT><FONT color=\"#B2AA7F\">我</FONT><FONT color=\"#FF7722\">は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=126079><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　未だ我</FONT><FONT color=\"#FF7722\">は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=126201><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　　  <FONT color=\"#66DDDD\">父よ　未だ我は</FONT>  　　　<br>　　　  아버지여, 아직 저는  　　　​\n"
+ "<Sync Start=126655><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#CC9960\">己</FONT><FONT color=\"#FF7722\">を知りがたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=127016><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#99BB9E\">己</FONT><FONT color=\"#FF7722\">を知りがたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=127143><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己</FONT><FONT color=\"#FF7722\">を</FONT><FONT color=\"#FF7722\">知りがたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=127378><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を</FONT><FONT color=\"#FF7722\">知</FONT><FONT color=\"#FF7722\">りがたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=127616><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を知</FONT><FONT color=\"#FF7722\">り</FONT><FONT color=\"#FF7722\">がたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=127864><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を知り</FONT><FONT color=\"#FF7722\">が</FONT><FONT color=\"#FF7722\">たし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=128112><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を知りが</FONT><FONT color=\"#FF7722\">た</FONT><FONT color=\"#FF7722\">し</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=128335><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を知りがた</FONT><FONT color=\"#FF7722\">し</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=128583><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br>　　  <FONT color=\"#66DDDD\">己を知りがたし</FONT>  　　<br>　　  제 자신을 알고 싶습니다  　　​\n"
+ "<Sync Start=130449><P Class=KRCC>\n"
+ "황력 2010년  　　　　　　　　　　<br>극동 사변 발발  　　　　　　　　　<br>패전국 일본은　　　　　　　　　　<br>신성 브리타니아 제국의 속령이 되어<br>에어리어 11이라 불리게 된다.　　　<b></b><br><b>　</b><br><b>　</b>\n"
+ "<Sync Start=132345><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#B2AA7F\">先</FONT><FONT color=\"#FF7722\">立つ兄らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=132776><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先</FONT><FONT color=\"#FF7722\">立</FONT><FONT color=\"#FF7722\">つ兄らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=133123><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立</FONT><FONT color=\"#FF7722\">つ</FONT><FONT color=\"#FF7722\">兄らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=133239><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立つ</FONT><FONT color=\"#FF7722\">兄</FONT><FONT color=\"#FF7722\">らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=134247><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立つ</FONT><FONT color=\"#B2AA7F\">兄</FONT><FONT color=\"#FF7722\">らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=134711><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立つ兄</FONT><FONT color=\"#FF7722\">ら</FONT><FONT color=\"#FF7722\">の</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=135095><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立つ兄ら</FONT><FONT color=\"#FF7722\">の</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=135224><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　　　　<FONT color=\"#66DDDD\">先立つ兄らの</FONT>　　　　　<br>　　　　　앞서간 형들의　　　　　​\n"
+ "<Sync Start=136456><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見</FONT><FONT color=\"#FF7722\">え</FONT><FONT color=\"#FF7722\">ない背中を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=136640><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見え</FONT><FONT color=\"#FF7722\">な</FONT><FONT color=\"#FF7722\">い背中を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=136874><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えな</FONT><FONT color=\"#FF7722\">い</FONT><FONT color=\"#FF7722\">背中を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=137123><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない</FONT><FONT color=\"#FF7722\">背</FONT><FONT color=\"#FF7722\">中を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=137576><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背</FONT><FONT color=\"#FF7722\">中</FONT><FONT color=\"#FF7722\">を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=138071><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背</FONT><FONT color=\"#B2AA7F\">中</FONT><FONT color=\"#FF7722\">を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=138304><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背中</FONT><FONT color=\"#FF7722\">を</FONT><FONT color=\"#FF7722\">追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=138567><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背中を</FONT><FONT color=\"#FF7722\">追</FONT><FONT color=\"#FF7722\">えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=138784><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背中を追</FONT><FONT color=\"#FF7722\">え</FONT><FONT color=\"#FF7722\">ば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=138976><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背中を追え</FONT><FONT color=\"#FF7722\">ば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=139513><P Class=KRCC>\n"
+ "그로부터 7년 후　　　　　　　　　<br>브리타니아의 지배에 대한 저항 세력<br>흑의 기사단이 결성된다. 　　　　　<br>다수의 레지스탕스를 흡수해  　　　<br>확대되는 흑의 기사단. 　　　　　　<b></b><br>　　 <FONT color=\"#66DDDD\">見えない背中を追えば</FONT> 　　<br>　　 보이지 않는 등을 뒤쫓으니 　　​\n"
+ "<Sync Start=140017><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#B2AA7F\">迷</FONT><FONT color=\"#FF7722\">いの一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140377><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷</FONT><FONT color=\"#FF7722\">い</FONT><FONT color=\"#FF7722\">の一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140769><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷い</FONT><FONT color=\"#FF7722\">の</FONT><FONT color=\"#FF7722\">一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=140906><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの</FONT><FONT color=\"#FF7722\">一</FONT><FONT color=\"#FF7722\">夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=141921><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの</FONT><FONT color=\"#B2AA7F\">一</FONT><FONT color=\"#FF7722\">夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142321><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一</FONT><FONT color=\"#FF7722\">夜</FONT><FONT color=\"#FF7722\">に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142729><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜</FONT><FONT color=\"#FF7722\">に</FONT><FONT color=\"#FF7722\">明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=142866><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に</FONT><FONT color=\"#FF7722\">明</FONT><FONT color=\"#FF7722\">星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=143817><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に</FONT><FONT color=\"#B2AA7F\">明</FONT><FONT color=\"#FF7722\">星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144017><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明</FONT><FONT color=\"#FF7722\">星</FONT><FONT color=\"#FF7722\">は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144258><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明</FONT><FONT color=\"#B2AA7F\">星</FONT><FONT color=\"#FF7722\">は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144457><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星</FONT><FONT color=\"#FF7722\">は</FONT><FONT color=\"#FF7722\">誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=144683><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#FF7722\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145201><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#CC9960\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145361><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星は</FONT><FONT color=\"#99BB9E\">誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145530><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星は誘</FONT><FONT color=\"#FF7722\">う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=145697><P Class=KRCC>\n"
+ "​　그 지도자, 제로의 정체는 바로 　<br>　과거 신성 브리타니아 제국에게　<br>　버려진 황자  　　　　　　　　　<br>　를루슈 비 브리타니아 　　　　　<br>　본인이었다.　　　　　　　　　<b></b>　<br><FONT color=\"#66DDDD\">迷いの一夜に明星は誘う</FONT><br>망설임의 어느 밤에 샛별이 유혹하네\n"
+ "<Sync Start=147639><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死</FONT><FONT color=\"#FF7722\">し</FONT><FONT color=\"#FF7722\">て終わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=148344><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死し</FONT><FONT color=\"#FF7722\">て</FONT><FONT color=\"#FF7722\">終わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=148506><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して</FONT><FONT color=\"#FF7722\">終</FONT><FONT color=\"#FF7722\">わらぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=149296><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終</FONT><FONT color=\"#FF7722\">わ</FONT><FONT color=\"#FF7722\">らぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=149484><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わ</FONT><FONT color=\"#FF7722\">ら</FONT><FONT color=\"#FF7722\">ぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=150161><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わら</FONT><FONT color=\"#FF7722\">ぬ</FONT><br>죽어도 끝나지 않는\n"
+ "<Sync Start=150402><P Class=KRCC>\n"
+ "<FONT color=\"#66DDDD\">死して終わらぬ</FONT><br>죽어도 끝나지 않는");
            }
            if (true)
            {
                param.Add(".tab[name=shake] textarea.input", "<Sync Start=145346><P Class=KRCC>\n"
+ "<font color=\"#dd88ff\">I believe</font>\n"
+ "<Sync Start=148752><P Class=KRCC>\n"
+ "<font color=\"#dd88ff\">that is where</font>\n"
+ "<Sync Start=151446><P Class=KRCC>\n"
+ "<font color=\"#dd88ff\">you can find</font>\n"
+ "<Sync Start=154941><P Class=KRCC>\n"
+ "<font color=\"#dd88ff\">whats really worth</font>\n"
+ "<Sync Start=158102><P Class=KRCC>\n"
+ "&nbsp;");
            }

            Script("initMain", new object[] { JsonConvert.SerializeObject(param) });
        }

        #endregion


        public void FillSync(string id)
        {
            //List<Smi> input = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            List<Smi> input = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            Smi.FillEmptySync(input);
            SetPreview(id, input, 100);
            string output = new SmiFile() { body = input }.ToTxt();
            Script("$val", new object[] { "#" + id + " > textarea.output", output });
        }

        public void Normalize(string id)
        {
            //List<Smi> input = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            List<Smi> input = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            Smi.Normalize(input);
            SetPreview(id, input, 100);
            string output = new SmiFile() { body = input }.ToTxt();
            Script("$val", new object[] { "#" + id + " > textarea.output", output });
        }

        public void Fusion(string id)
        {
            string[] inputSync = Script("$val", new object[] { "#" + id + " textarea.inputSync" }).Replace("\r\n", "\n").Split('\n');
            string[] inputText = Script("$val", new object[] { "#" + id + " textarea.inputText" }).Replace("\r\n", "\n").Split('\n');
            string output = "";
            for (int i = 0; i * 2 < inputSync.Length && i < inputText.Length; i++)
                output += inputSync[i * 2] + "\n" + inputText[i] + "\n";

            Script("$val", new object[] { "#" + id + " textarea.output", output });
        }

        public void Combine(string id)
        {
            //List<Smi> inputUpper = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " textarea.inputUpper" })).body;
            //List<Smi> inputLower = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " textarea.inputLower" })).body;
            List<Smi> inputUpper = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " textarea.inputUpper" })).body;
            List<Smi> inputLower = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " textarea.inputLower" })).body;
            List<Smi> result = Combiner.Combine(inputUpper, inputLower);
            SetPreview(id, result, 100);
            string output = new SmiFile() { body = result }.ToTxt();
            Script("$val", new object[] { "#" + id + " > textarea.output", output });
        }

        public void Devide(string id)
        {
            //List<Smi> input = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            List<Smi> input = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            Tuple<List<Smi>, List<Smi>> result = Devider.Devide(input);
            Script("$val", new object[] { "#" + id + " > textarea.outputUpper", Smi.Smi2txt(result.Item1) });
            Script("$val", new object[] { "#" + id + " > textarea.outputLower", Smi.Smi2txt(result.Item2) });
        }

        public void Shake(string id)
        {
            //List<Smi> input = SmiFile.FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            List<Smi> input = new SmiFile().FromTxt(Script("$val", new object[] { "#" + id + " > textarea.input" })).body;
            List<Smi> result = Shaker.Shake(input);
            SetPreview(id, result);
            Script("$val", new object[] { "#" + id + " > textarea.output", Smi.Smi2txt(result) });
        }

        public void Nico(string id)
        {
            JObject nicos = JObject.Parse(Script("getNicoValue", new object[] { id }));
            int width = Convert.ToInt32(nicos["width"].ToString());
            JArray values = (JArray)nicos["value"];

            List<NicoNico.NicoLine> nicoLines = new List<NicoNico.NicoLine>();
            foreach (JToken value in values)
            {
                int   line  = value["line" ].ToObject<int>();
                int   start = value["start"].ToObject<int>();
                int   end   = value["end"  ].ToObject<int>();
                string text = value["text" ].ToString();
                if (start >= end) continue;

                nicoLines.Add(new NicoNico.NicoLine()
                {
                    line  = line,
                    start = start,
                    end   = end,
                    text  = text,
                    width = Smi.GetLineWidth(text),
                });
            }
            nicoLines.Sort((a, b) => (a.start - b.start));

            List<Smi> result = NicoNico.Nico(nicoLines, width);
            SetPreview(id, result);
            Script("$val", new object[] { "#" + id + " > textarea.output", Smi.Smi2txt(result) });
        }

        // 어쩌다 보니 급조한 부분이긴 한데 음...
        private void SetPreview(string id, List<Smi> smis)
        {
            SetPreview(id, smis, 42);
        }
        private void SetPreview(string id, List<Smi> smis, int interval)
        {
            List<string> previews = new List<string>();
            foreach (Smi smi in smis)
            {
                //List<Converter.Span> spans = Converter.Span.FromSmi(smi.text);
                //string html = Converter.Span.ToHtml(spans);
                List<Attr> attrs = smi.ToAttr();
                string html = Attr.ToHtml(attrs);
                //Console.WriteLine(html);
                previews.Add(html);
            }
            string json = JsonConvert.SerializeObject(previews);
            Script("setPreview", new object[] { id, json, interval });
        }
    }
}
